"use client";
import { Printer, ArrowUpRight } from 'lucide-react';
import type { MemberData } from './page';
import { PersonalitySummary } from './personality-assessment';
import { programModules } from '../../lib/program-data';
import { describeLifePath } from '../../lib/life-paths';
import { explainPosition } from '../../lib/astrology-engine';

export function MemberProfile({data,printView=false}:{data:MemberData;printView?:boolean}) {
  const answers=Object.fromEntries(data.responses.map(row=>[row.question_key,row.answer]));
  const text=(key:string)=>Array.isArray(answers[key])?(answers[key] as unknown[]).join(' · '):typeof answers[key]==='string'?String(answers[key]):'';
  const energy=data.derived?.energy??{};
  const lifePath=Number(energy.lifePath);
  const meaning=describeLifePath(lifePath);
  function entry(label:string,key:string) {return text(key)?<div className="report-entry" key={key}><h3>{label}</h3><p>{text(key)}</p></div>:null;}
  function assets(key:string,title:string) {
    const options=programModules.flatMap(m=>m.questions).find(q=>q.key===key)?.options?.filter(o=>!['None yet','Not sure'].includes(o))??[];
    const chosen=Array.isArray(answers[key])?answers[key] as string[]:[];
    const known=chosen.length>0&&!chosen.includes('Not sure');
    return <div className="report-assets"><h3>{title}</h3>{!known?<p>Not confirmed yet.</p>:<><div><span className="asset-state">In place</span><p>{options.filter(o=>chosen.includes(o)).join(' · ')||'None selected yet'}</p></div><div><span className="asset-state pending">Still to confirm or build</span><p>{options.filter(o=>!chosen.includes(o)).join(' · ')||'All listed assets are in place'}</p></div></>}</div>;
  }
  return <div className={`portal-view-stack profile-page ${printView?'standalone-report':''}`}>
    <div className="portal-page-heading report-controls"><div><span className="portal-eyebrow">YOUR ABLE PROFILE</span><h1>Your profile.</h1></div><button className="profile-print" onClick={()=>printView?window.print():window.open('/member/report','_blank','noopener')}><Printer size={18}/>{printView?'Print / save PDF':'Open printable profile'}</button></div>
    <article className="able-report">
      <header className="report-masthead"><img src="/able1self-logo.png" alt="ABLE1SELF"/><span>PERSONAL PROFILE</span><span>{data.profile.overallProgress}% complete</span></header>
      <div className="report-name">{data.profile.avatarUrl&&<img src={data.profile.avatarUrl} alt=""/>}<div><h1>{data.profile.displayName}</h1>{data.profile.professionalTitle&&<p>{data.profile.professionalTitle}</p>}{data.profile.bio&&<p>{data.profile.bio}</p>}</div></div>
      <section className="report-core"><div className="report-kicker">CORE IDENTITY / ENGINE 2.0</div>{data.identity?<><h2>{data.identity.archetype.name}</h2><p className="report-deck">{data.identity.archetype.tagline}</p><p>{data.identity.archetype.identity}</p><div className="report-axis">{data.identity.axes.map(axis=><div key={axis.axis}><span>{axis.label}</span><strong>{axis.poleName}</strong></div>)}</div><div className="report-grid">{[['Strengths',data.identity.archetype.strengths],['Watch points',data.identity.archetype.blindSpots],['Ideal rooms',data.identity.archetype.idealRooms]].map(([label,items])=><div key={label as string}><h3>{label as string}</h3><ul>{(items as string[]).map(item=><li key={item}>{item}</li>)}</ul></div>)}</div><p className="report-note">{data.identity.provisional?'Provisional profile. Your remaining responses may refine it.':'A reflection of your answers, not a fixed definition of who you are.'}</p></>:<p>Complete Analyze to reveal your core identity.</p>}</section>
      <section className="report-chapter"><header><span>A</span><div><small>01 / SELF-KNOWLEDGE</small><h2>Analyze</h2></div></header><PersonalitySummary value={answers.a1_assessment}/><div className="report-grid report-signs">{(['sun','moon','rising'] as const).map(kind=>{const sign=energy[`${kind}Sign`];return typeof sign==='string'?<div key={kind}><h3>{kind==='rising'?'Rising sign':`${kind[0].toUpperCase()}${kind.slice(1)} sign`}</h3><strong>{sign}</strong><p>{explainPosition(kind,sign)}</p></div>:null;})}</div>{meaning&&<div className="report-numerology"><h3>Life path {lifePath} / {meaning.title}</h3><p>{meaning.reading}</p><p><strong>For your brand:</strong> {meaning.brandMove}</p><small>Numerology and astrology are interpretive reflection tools, not scientific assessments.</small></div>}<div className="report-reflections">{entry('Who are you beyond your work?','a3_self')}{entry('Who are you becoming?','a3_becoming')}{entry('What do you most want to build or achieve?','a3_dream')}{entry('What do people come to you for?','a3_gifts')}{entry('What would the world miss without your contribution?','a3_contribution')}</div></section>
      <section className="report-chapter"><header><span>B</span><div><small>02 / YOUR EXPRESSION</small><h2>Brand</h2></div></header><blockquote>{text('b3_edit')||data.derived?.brandStatement||'Your brand statement will take shape as you complete Brand.'}</blockquote>{entry('Purpose','b3_why')}{entry('Brand voice','b3_voice')}{data.derived?.styleArchetype&&<div className="report-entry"><h3>Visual identity</h3><p>{data.derived.styleArchetype}</p></div>}<div className="report-grid two">{assets('b2_business_setup','Business foundations')}{assets('b2_digital_assets','Brand assets')}</div>{entry('Where support would help','b2_support')}</section>
      <section className="report-chapter"><header><span>L</span><div><small>03 / YOUR OPPORTUNITY</small><h2>Leverage</h2></div></header>{entry('Your positioning','l3_profile_line')}<div className="report-grid two">{entry('People you can help','l2_past_self')}{entry('Your offer','l2_offer')}{entry('Problem you understand','l2_problem')}{entry('Your solution','l2_solution')}{entry('Evidence','l2_proof')}{entry('Pricing and delivery','l2_price')}{entry('Existing network','l1_top5')}{entry('Discovery channels','l1_channels')}{entry('Your story','l3_story')}{entry('Next step for your audience','l3_action')}</div></section>
      <section className="report-chapter"><header><span>E</span><div><small>04 / YOUR DIRECTION</small><h2>Embark</h2></div></header><div className="report-goal"><h3>Your goal</h3><p>{text('e1_goal')||'Your goal is still taking shape.'}</p><span>{text('e1_horizon')||'Timeline not selected'}</span></div>{entry('Success looks like','e1_success')}{entry('Your first move','e1_next_action')}<ol className="report-milestones">{['e2_m1','e2_m2','e2_m3'].filter(key=>text(key)).map(key=><li key={key}>{text(key)}</li>)}</ol><div className="report-grid two">{entry('Accountability partner','e3_partner')}{entry('Check-in rhythm','e3_checkin')}{entry('Your commitment','e3_commitment')}{entry('When you get stuck','e2_if_stuck')}</div>{data.plan.length>0&&<div className="report-targets"><h3>Current commitments</h3>{data.plan.map(item=><div className="report-entry" key={item.id}><strong>{item.title}</strong><p>{item.success_metric}</p><small>{item.due_date?`Due ${item.due_date} · `:''}{item.status.replaceAll('_',' ')}</small></div>)}</div>}</section>
      <footer className="report-footer"><span>ABLE1SELF</span><span>Personal. Considered. In motion.</span></footer>
    </article>
    {!printView&&<details className="report-drilldown"><summary>Explore your saved answers <ArrowUpRight size={17}/></summary>{['A','B','L','E'].map(stage=><section key={stage}><h2>{stage} / Saved reflections</h2>{programModules.filter(m=>m.stage===stage).flatMap(m=>m.questions.filter(q=>q.control!=='birth'&&q.control!=='personality'&&q.control!=='derived').map(q=>entry(q.prompt,q.key)))}</section>)}</details>}
  </div>;
}
